import JSZip from "jszip";
import { saveAs } from "file-saver";
import type { ProjectBlueprint } from "@/lib/schema";
import { buildArtifacts } from "./render";

export async function downloadBlueprintZip(bp: ProjectBlueprint) {
  const zip = new JSZip();
  const artifacts = bp.artifacts.length ? bp.artifacts : buildArtifacts(bp);
  for (const artifact of artifacts) {
    zip.file(artifact.path, artifact.content);
  }
  zip.file(
    "README.md",
    `# ${bp.decisions.productName} - SpekDulu Export

1. Extract this ZIP into your project root.
2. Confirm \`.cursor/skills/spekdulu/SKILL.md\` exists.
3. In Cursor, ask: "Read the SpekDulu Skill and implement Phase 1 only. Stop when acceptance criteria pass."

Generated by SpekDulu (${bp.provider} provider).
`,
  );
  const blob = await zip.generateAsync({ type: "blob" });
  saveAs(blob, `${bp.decisions.productName.toLowerCase().replace(/\s+/g, "-")}-spekdulu.zip`);
}

export function buildCursorInstruction(bp: ProjectBlueprint): string {
  return `Read .cursor/skills/spekdulu/SKILL.md, PRODUCT.md, DESIGN.md, IMPLEMENTATION.md, and TASKS.md. Implement Phase 1 for ${bp.decisions.productName} only. Follow Build Now features and stop when all acceptance criteria pass. Do not implement Do Not Build features.`;
}
